// <auto-generated />
using System;
using Guest_Management_Tool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Guest_Management_Tool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241214200546_I_added_data_inthe_table")]
    partial class I_added_data_inthe_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Guest_Management_Tool.Models.GuestInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("accessReq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("birthDate")
                        .HasColumnType("date");

                    b.Property<string>("contactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dietPref")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dietRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("emailAdd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("favoriteFandB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("foodAllerg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("medReq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prevEvents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("resDate")
                        .HasColumnType("date");

                    b.Property<string>("wellnessPref")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GuestInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            accessReq = "No preferences",
                            address = "123 Share St., Vancouver BC V1V 2A3",
                            birthDate = new DateOnly(2024, 11, 23),
                            contactNo = "990 123456",
                            dietPref = "All vegetarian food",
                            dietRequest = "None",
                            emailAdd = "markdelacruz111@gmail.com",
                            fName = "Mark",
                            favoriteFandB = "No pork and soda",
                            feedback = "5 stars fro the good service",
                            foodAllerg = "Shrimp",
                            lName = "Dela Cruz",
                            medReq = "Should need to have a near pharmacy",
                            prevEvents = "Christmas with my relatives",
                            resDate = new DateOnly(2024, 11, 23),
                            wellnessPref = "Enthusiast to go gym nearby"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
